backend:
  name: github
  repo: antonrize/WILL
  branch: main
  base_url: https://proxy-flame-seven.vercel.app/api   # ← add /api
  auth_endpoint: auth
  site_domain: antonrize.github.io

publish_mode: editorial_workflow

media_folder: "assets/img" # ????? ??? ???????????
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "???????? ????????"
    files:
      - file: "index.md"
        label: "??????? ????????"
        name: "index"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "??????????", name: "body", widget: "markdown"}
      - file: "about.md"
        label: "? ??????? (About)"
        name: "about"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "?????????", name: "title", widget: "string"}
          - {label: "??????????", name: "body", widget: "markdown"}
      - file: "geometry.md"
        label: "????????? WILL"
        name: "geometry"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "?????????", name: "title", widget: "string"}
          - {label: "??????????", name: "body", widget: "markdown"}
  - name: "posts"
    label: "????? (??????)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "?????????", name: "title", widget: "string"}
      - {label: "????", name: "date", widget: "datetime"}
      - {label: "??????????", name: "body", widget: "markdown"}

  # Home page structured data
  - name: "home"
    label: "Home Content (YAML)"
    files:
      - file: "_data/home.yml"
        label: "Home Page Text"
        name: "home_yaml"
        fields:
          - {label: "YAML", name: "body", widget: "yaml"}
